#ifndef SND_PARSERS_PE_STATUS_H
#define SND_PARSERS_PE_STATUS_H

#include <sindri/common/macros.h>
#include <sindri/status.h>

SND_BEGIN_EXTERN_C

typedef enum _SND_PE_PARSER_STATUS_CODE {
    // Headers
    SND_STATUS_HEADER_DOS_TRUNCATED = SND_MAKE_STATUS(SND_FACILITY_PARSER_PE, 1),
    SND_STATUS_HEADER_DOS_SIGNATURE_INVALID,
    SND_STATUS_HEADER_NT_TRUNCATED,
    SND_STATUS_HEADER_NT_SIGNATURE_INVALID,
    SND_STATUS_HEADER_OPTIONAL_SIGNATURE_INVALID,
    SND_STATUS_HEADER_OFFSET_INVALID,

    // Data Directories
    SND_STATUS_DIRECTORY_ENTRY_MISSING,
    SND_STATUS_DIRECTORY_ENTRY_INVALID,

    // Import Directory
    SND_STATUS_IMPORT_DESCRIPTOR_INVALID,
    SND_STATUS_IMPORT_DESCRIPTOR_OVERFLOW,
    SND_STATUS_IMPORT_NAME_INVALID,
    SND_STATUS_IMPORT_THUNK_INVALID,
    SND_STATUS_IMPORT_THUNK_OUT_OF_BOUNDS,
    SND_STATUS_IMPORT_THUNK_OVERFLOW,

    // Export Directory
    SND_STATUS_EXPORT_DIRECTORY_NULL,
    SND_STATUS_EXPORT_DIRECTORY_INVALID,
    SND_STATUS_EXPORT_DIRECTORY_OVERFLOW,
    SND_STATUS_EXPORT_TABLE_EMPTY,
    SND_STATUS_EXPORT_SYMBOL_MISSING,
    SND_STATUS_EXPORT_ORDINAL_INVALID,
    SND_STATUS_EXPORT_ORDINAL_OVERFLOW,
    SND_STATUS_EXPORT_ORDINAL_OUT_OF_RANGE,
    SND_STATUS_EXPORT_FORWARDER_UNSUPPORTED,
    SND_STATUS_EXPORT_FORWARDER_EXCEEDED,
    SND_STATUS_EXPORT_FORWARDER_INVALID,

    // Relocation Directory
    SND_STATUS_RELOCATION_DIRECTORY_TRUNCATED,
    SND_STATUS_RELOCATION_DIRECTORY_OUT_OF_BOUNDS,
    SND_STATUS_RELOCATION_DIRECTORY_OVERFLOW,
    SND_STATUS_RELOCATION_BLOCK_INVALID,
    SND_STATUS_RELOCATION_ENTRY_OVERFLOW,
    SND_STATUS_PE_RELOCATION_PATCH_OUT_OF_RANGE,
    SND_STATUS_PE_RELOCATION_TYPE_UNSUPPORTED,
} snd_pe_parser_status_code_t;

/**
 * @brief Converts a PE parser status code into a human-readable description string.
 * @param code Error code value.
 * @retval Pointer to a string description, or the default error message.
 */
const char *snd_pe_parser_status_to_string(int code);

SND_END_EXTERN_C

#endif // SND_PARSERS_PE_STATUS_H
